# Generated by Django 6.0.8 on 2026-09-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='member_id',
            field=models.CharField(blank=True, help_text='Roll number for students or Employee ID for staff.', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Librarian / Admin'), ('STAFF', 'Faculty / Staff'), ('STUDENT_PG', 'Postgraduate (PG)'), ('STUDENT_UG', 'Undergraduate (UG)')], default='STUDENT_UG', help_text='Designates borrowing quotas and renewal permissions.', max_length=20),
        ),
    ]
